TOP_PATH := $(call my-dir)

include $(TOP_PATH)/src/Android.mk

include $(TOP_PATH)/adat/Android.mk
include $(TOP_PATH)/alinco/Android.mk
include $(TOP_PATH)/amsat/Android.mk
include $(TOP_PATH)/aor/Android.mk
include $(TOP_PATH)/ars/Android.mk
include $(TOP_PATH)/celestron/Android.mk
include $(TOP_PATH)/drake/Android.mk
include $(TOP_PATH)/dummy/Android.mk
include $(TOP_PATH)/easycomm/Android.mk
include $(TOP_PATH)/ether6/Android.mk
include $(TOP_PATH)/flexradio/Android.mk
include $(TOP_PATH)/fodtrack/Android.mk
include $(TOP_PATH)/gs232a/Android.mk
include $(TOP_PATH)/heathkit/Android.mk
include $(TOP_PATH)/icom/Android.mk
include $(TOP_PATH)/jrc/Android.mk
include $(TOP_PATH)/kachina/Android.mk
include $(TOP_PATH)/kenwood/Android.mk
include $(TOP_PATH)/kit/Android.mk
include $(TOP_PATH)/lowe/Android.mk
include $(TOP_PATH)/m2/Android.mk
include $(TOP_PATH)/meade/Android.mk
include $(TOP_PATH)/pcr/Android.mk
include $(TOP_PATH)/prm80/Android.mk
include $(TOP_PATH)/racal/Android.mk
include $(TOP_PATH)/rft/Android.mk
include $(TOP_PATH)/rotorez/Android.mk
include $(TOP_PATH)/rs/Android.mk
include $(TOP_PATH)/sartek/Android.mk
include $(TOP_PATH)/skanti/Android.mk
include $(TOP_PATH)/spid/Android.mk
include $(TOP_PATH)/tapr/Android.mk
include $(TOP_PATH)/tentec/Android.mk
include $(TOP_PATH)/ts7400/Android.mk
include $(TOP_PATH)/tuner/Android.mk
include $(TOP_PATH)/uniden/Android.mk
include $(TOP_PATH)/winradio/Android.mk
include $(TOP_PATH)/wj/Android.mk
include $(TOP_PATH)/yaesu/Android.mk
