TOP_PATH := $(call my-dir)

include $(TOP_PATH)/src/Android.mk

include $(TOP_PATH)/rigs/adat/Android.mk
include $(TOP_PATH)/rigs/alinco/Android.mk
include $(TOP_PATH)/rigs/amsat/Android.mk
include $(TOP_PATH)/rigs/aor/Android.mk
include $(TOP_PATH)/rigs/ars/Android.mk
include $(TOP_PATH)/rigs/celestron/Android.mk
include $(TOP_PATH)/rigs/drake/Android.mk
include $(TOP_PATH)/rigs/dummy/Android.mk
include $(TOP_PATH)/rigs/easycomm/Android.mk
include $(TOP_PATH)/rigs/ether6/Android.mk
include $(TOP_PATH)/rigs/flexradio/Android.mk
include $(TOP_PATH)/rigs/fodtrack/Android.mk
include $(TOP_PATH)/rigs/gs232a/Android.mk
include $(TOP_PATH)/rigs/heathkit/Android.mk
include $(TOP_PATH)/rigs/icom/Android.mk
include $(TOP_PATH)/rigs/jrc/Android.mk
include $(TOP_PATH)/rigs/kachina/Android.mk
include $(TOP_PATH)/rigs/kenwood/Android.mk
include $(TOP_PATH)/rigs/kit/Android.mk
include $(TOP_PATH)/rigs/lowe/Android.mk
include $(TOP_PATH)/rigs/m2/Android.mk
include $(TOP_PATH)/rigs/meade/Android.mk
include $(TOP_PATH)/rigs/pcr/Android.mk
include $(TOP_PATH)/rigs/prm80/Android.mk
include $(TOP_PATH)/rigs/racal/Android.mk
include $(TOP_PATH)/rigs/rft/Android.mk
include $(TOP_PATH)/rigs/rotorez/Android.mk
include $(TOP_PATH)/rigs/rs/Android.mk
include $(TOP_PATH)/rigs/sartek/Android.mk
include $(TOP_PATH)/rigs/skanti/Android.mk
include $(TOP_PATH)/rigs/spid/Android.mk
include $(TOP_PATH)/rigs/tapr/Android.mk
include $(TOP_PATH)/rigs/tentec/Android.mk
include $(TOP_PATH)/rigs/ts7400/Android.mk
include $(TOP_PATH)/rigs/tuner/Android.mk
include $(TOP_PATH)/rigs/uniden/Android.mk
include $(TOP_PATH)/rigs/winradio/Android.mk
include $(TOP_PATH)/rigs/wj/Android.mk
include $(TOP_PATH)/rigs/yaesu/Android.mk
