#   Copyright (C) 1997 - 2001 Free Software Foundation, Inc.

#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License along
#    with this program; if not, write to the Free Software Foundation, Inc.,
#    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

# Please email any bugs, comments, and/or additions to this file to:
# hamlib-developer@lists.sourceforge.net

set TESTLOC "$srcdir/testloc"

#
# Here are the tests
#

# TODO: upcase locator
proc test_loc1 { test loc } {

	global TESTLOC
	set tmp [exec $TESTLOC $loc]

	set pat "Locator1: $loc\n.*Recoded: $loc$"
	if [regexp $pat $tmp] {
		pass "$test"
	} else {
		clone_output "Expected locator: $loc, got:\n$tmp"
		fail "$test"
	}
}

test_loc1 "Simple recorded loc" IN98EC
test_loc1 "Simple recorded loc" EM19OV
test_loc1 "Simple recorded loc" DM33DX
test_loc1 "Simple recorded loc" IO93LA
test_loc1 "Simple recorded loc" IO93MA
test_loc1 "Simple recorded loc" IO93NA

