#   Copyright (C) 1997 - 2001 Free Software Foundation, Inc.

#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License along
#    with this program; if not, write to the Free Software Foundation, Inc.,
#    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

# Please email any bugs, comments, and/or additions to this file to:
# hamlib-developer@lists.sourceforge.net

set TESTFREQ "$srcdir/testfreq"

#
# Here are the tests
#

proc test_freq { test } {

	global TESTFREQ
	set tmp [exec $TESTFREQ]

	set pat ".*GHz.2. = 2000000000\nGHz.4. = 4000000000\nGHz.5. = 5000000000\nGHz.1.3. = 1300000000\nGHz.1.234567890. = 1234567890\nGHz.123.456789012. = 123456789012$"
	if [regexp $pat $tmp] {
		pass "$test"
	} else {
		clone_output "Expected GHz holding on >32bits, got:\n$tmp"
		fail "$test"
		puts $pat
	}
}

test_freq ">32bit freq's"

