.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH RIGD "8" "August 23, 2002" "Hamlib"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
rigd \- Hamlib rig service daemon
.SH SYNOPSIS
.B rpc.rigd
[\fIOPTION\fR]...
.SH DESCRIPTION
The \fBrigd\fP program is a Hamlib rig daemon that handles RPC client requests.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics, 
.\" respectively.
Keep in mind that \fBHamlib\fP is still ALPHA level software. 
A lof of stuff hasn't been tested thoroughly, and the API may change
without publicised notice. Please report bugs and feedback at
the e-mail address given in the REPORTING BUGS section.
.SH OPTIONS
This program follow the usual GNU command line syntax, with long
options starting with two dashes (`-').
A summary of options is included below.
.TP
.B \-m, \-\-model=id
Select radio model number. See model list.
.TP
.B \-r, --rig-file=device
Use \fBdevice\fP as the file name of the radio to operate on.
.TP
.B \-p, --ptt-file=device
Use \fBdevice\fP as the file name of the Push-To-Talk device to operate on.
.TP
.B \-d, --dcd-file=device
Use \fBdevice\fP as the file name of the Data Carrier Detect device 
to operate on.
.TP
.B \-p, --ptt-type=type
Use \fBtype\fP device as the kind of the Push-To-Talk device to operate on.
Supported types are RIG, DTR, RTS, PARALLEL, NONE.
.TP
.B \-d, --dcd-type=type
Use \fBtype\fP device as the kind of the Data Carrier Detect device 
to operate on.
Supported types are RIG, DSR, CTS, PARALLEL, NONE.
.TP
.B \-s, --serial-speed=baud
Set serial speed to \fBbaud\fP rate. Uses maximal rig speed as default.
.TP
.B \-c, --civaddr=id
Use \fBid\fP as the CI-V address to communicate with the rig. Only for Icom rigs.
.TP
.B \-C, \-\-set\-conf=parm=val[,parm=val]*
Set config parameter.
.TP
.B \-v, \-\-verbose
Set verbose mode, cumulative.
.TP
.B \-h, \-\-help
Show summary of options and exit.
.TP
.B \-V, \-\-version
Show version of program and exit.

.PP
Please note that the backend for the radio to be controlled, 
or the radio itself may not support some commands. In that case, 
the operation will fail with a standard error code.

.SH AUTHOR
Written by Stephane Fillod.
.SH BUGS
No authentication whatsoever. Could be done through domain restriction though.
Please ask if stronger security needed.
.PP
No more than one rig can be controlled on a system. rpc.rigd does not
support multi-rigs (hint: run rpc.rigd on a different port).
.PP
This almost empty section...
.SH REPORTING BUGS
Report bugs to <hamlib-developer@users.sourceforge.net>.
.br
I'm already aware of the bug in the previous section :-)
.SH COPYRIGHT
Copyright \(co 2000-2002 Stephane Fillod.
.br
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY
or FITNESS FOR A PARTICULAR PURPOSE.
.SH SEE ALSO
.BR rigctl (1)

