/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "rpcrig.h"

bool_t
xdr_vfo_x (XDR *xdrs, vfo_x *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_freq_s (XDR *xdrs, freq_s *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, &objp->f1))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->f2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_model_x (XDR *xdrs, model_x *objp)
{
	register int32_t *buf;

	 if (!xdr_u_int (xdrs, objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_freq_res (XDR *xdrs, freq_res *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->rigstatus))
		 return FALSE;
	switch (objp->rigstatus) {
	case 0:
		 if (!xdr_freq_s (xdrs, &objp->freq_res_u.freq))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}

bool_t
xdr_freq_arg (XDR *xdrs, freq_arg *objp)
{
	register int32_t *buf;

	 if (!xdr_vfo_x (xdrs, &objp->vfo))
		 return FALSE;
	 if (!xdr_freq_s (xdrs, &objp->freq))
		 return FALSE;
	return TRUE;
}
