/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RPCRIG_H_RPCGEN
#define _RPCRIG_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


typedef u_int vfo_x;

struct freq_s {
	u_int f1;
	u_int f2;
};
typedef struct freq_s freq_s;

typedef u_int model_x;

struct freq_res {
	int rigstatus;
	union {
		freq_s freq;
	} freq_res_u;
};
typedef struct freq_res freq_res;

struct freq_arg {
	vfo_x vfo;
	freq_s freq;
};
typedef struct freq_arg freq_arg;

#define RIGPROG 0x20000099
#define RIGVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define GETMODEL 1
extern  model_x * getmodel_1(void *, CLIENT *);
extern  model_x * getmodel_1_svc(void *, struct svc_req *);
#define SETFREQ 10
extern  int * setfreq_1(freq_arg *, CLIENT *);
extern  int * setfreq_1_svc(freq_arg *, struct svc_req *);
#define GETFREQ 11
extern  freq_res * getfreq_1(vfo_x *, CLIENT *);
extern  freq_res * getfreq_1_svc(vfo_x *, struct svc_req *);
extern int rigprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define GETMODEL 1
extern  model_x * getmodel_1();
extern  model_x * getmodel_1_svc();
#define SETFREQ 10
extern  int * setfreq_1();
extern  int * setfreq_1_svc();
#define GETFREQ 11
extern  freq_res * getfreq_1();
extern  freq_res * getfreq_1_svc();
extern int rigprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_vfo_x (XDR *, vfo_x*);
extern  bool_t xdr_freq_s (XDR *, freq_s*);
extern  bool_t xdr_model_x (XDR *, model_x*);
extern  bool_t xdr_freq_res (XDR *, freq_res*);
extern  bool_t xdr_freq_arg (XDR *, freq_arg*);

#else /* K&R C */
extern bool_t xdr_vfo_x ();
extern bool_t xdr_freq_s ();
extern bool_t xdr_model_x ();
extern bool_t xdr_freq_res ();
extern bool_t xdr_freq_arg ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RPCRIG_H_RPCGEN */
