#
# Makefile for AESStringCrypt test script (Windows)
# Copyright (C) 2007, 2008, 2009, 2012, 2015
# Paul E. Jones <paulej@packetizer.com>
#
# This software is licensed as "freeware."  Permission to distribute
# this software in source and binary forms is hereby granted without a
# fee.  THIS SOFTWARE IS PROVIDED 'AS IS' AND WITHOUT ANY EXPRESSED OR
# IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
# THE AUTHOR SHALL NOT BE HELD LIABLE FOR ANY DAMAGES RESULTING FROM THE
# USE OF THIS SOFTWARE, EITHER DIRECTLY OR INDIRECTLY, INCLUDING, BUT
# NOT LIMITED TO, LOSS OF DATA OR DATA BEING RENDERED INACCURATE.
#

CC	= cl.exe

LINK	= link.exe

RM	= del /q

LIBS	= $(conlibs) advapi32.lib

CFLAGS	= -D _CRT_SECURE_NO_WARNINGS /EHsc /O2 /W3

OBJS	= sctest.obj AESStringCrypt.obj aes.obj sha256.obj

sctest.exe: $(OBJS)
	$(LINK) $(conflags) -out:$@ $(OBJS) $(LIBS)

%.obj: %.c %.h
	$(CC) $(CFLAGS) $(cflags) $(cvars) -c $*.c

clean:
	$(RM) *.obj sctest.exe

