
noinst_LTLIBRARIES = libhamlib-flexradio.la
libhamlib_flexradio_la_SOURCES = flexradio.c flexradio.h sdr1k.c dttsp.c \
    smartsdr.c smartsdr_caps.h smartsdr_priv.h \
    smartsdr_conf.c smartsdr_conf.h \
    smartsdr_level.c smartsdr_level.h \
    smartsdr_props.c smartsdr_props.h \
    smartsdr_rig.c smartsdr_rig.h \
    smartsdr_session.c smartsdr_session.h \
    smartsdr_slice.c smartsdr_slice.h \
    smartsdr_stream.c smartsdr_stream.h \
    smartsdr_vita.c smartsdr_vita.h

EXTRA_DIST = FLEXRADIO.md
