.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH ROTD "8" "22 September 2002" "Hamlib"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
rotd \- Hamlib rotator service daemon
.SH SYNOPSIS
.B rpc.rotd
[\fIOPTION\fR]...
.SH DESCRIPTION
The \fBrotd\fP program is a Hamlib rotator daemon that handles RPC client requests.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics, 
.\" respectively.
Keep in mind that \fBHamlib\fP is still ALPHA level software. 
A lof of stuff hasn't been tested thoroughly, and the API may change
without publicised notice. Please report bugs and feedback at
the e-mail address given in the REPORTING BUGS section.
.SH OPTIONS
This program follow the usual GNU command line syntax, with long
options starting with two dashes (`-').
A summary of options is included below.
.TP
.B \-m, \-\-model=id
Select rotator model number. See model list.
.TP
.B \-r, --rot-file=device
Use \fBdevice\fP as the file name of the rotator to operate on.
.TP
.B \-s, --serial-speed=baud
Set serial speed to \fBbaud\fP rate. Uses maximal rotator speed as default.
.TP
.B \-C, \-\-set\-conf=parm=val[,parm=val]*
Set config parameter.
.TP
.B \-t, --prog=number
Use \fBnumber\fP as the RPC program number. The default is 536873369.
.TP
.B \-v, \-\-verbose
Set verbose mode, cumulative (BUG, ERR, WARN, VERBOSE, TRACE).
.TP
.B \-h, \-\-help
Show summary of options and exit.
.TP
.B \-V, \-\-version
Show version of program and exit.

.PP
Please note that the backend for the rotator to be controlled, 
or the rotator itself may not support some commands. In that case, 
the operation will fail with a standard error code.

.SH AUTHOR
Written by Stephane Fillod.
.SH BUGS
No authentication whatsoever. Could be done through domain restriction though.
Please ask if stronger security needed.
.PP
This almost empty section...
.SH REPORTING BUGS
Report bugs to <hamlib-developer@users.sourceforge.net>.
.br
I'm already aware of the bug in the previous section :-)
.SH COPYRIGHT
Copyright \(co 2000-2002 Stephane Fillod.
Contributed by Francois Retief <fgretief@sun.ac.za>.
.br
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY
or FITNESS FOR A PARTICULAR PURPOSE.
.SH SEE ALSO
.BR rotctl (1)

